version: "3"
services:
    # バックエンド
    backend:
        container_name: backend_go_dockerlec
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: dev
        tty: true
        stdin_open: true
        volumes:
            - type: bind
              source: ./backend/app
              target: /src
        ports:
            - 8080:8080
    